sudo apt install -y smbclient
cd /tmp
wget http://gdlp01.c-wss.com/gds/6/0100004596/05/linux-capt-drv-v271-uken.tar.gz
tar -zxvf linux-capt-drv-v271-uken.tar.gz
cd /tmp/linux-capt-drv-v271-uken/64-bit_Driver/Debian
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install -y libc6:i386 libpopt0:i386 zlib1g:i386 libxml2:i386 libstdc++6:i386
sudo dpkg -i cndrvcups-common_3.21-1_amd64.deb
sudo dpkg -i cndrvcups-capt_2.71-1_amd64.deb
sudo apt install -f -y
sudo rm /etc/cups/printers.conf
sudo cat > /etc/cups/printers.conf <<EOF
# Printer configuration file for CUPS v2.2.1
# Written by cupsd
# DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING
<Printer CanonLBP6020>
UUID urn:uuid:2f3269a1-4c18-3f5e-7172-7b3608816546
Info CanonLBP6020
Location DESKTOP-926B24D
MakeModel Canon LBP6020 CAPT (UK)
DeviceURI smb://user:12345@DESKTOP-926B24D/CanonLBP6020
State Idle
StateTime 1503670008
ConfigTime 1503670015
Type 8393860
Accepting Yes
Shared No
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
EOF
sudo service cups restart
