#!/bin/sh
# Настройка полного технологическог журнала
sudo mkdir -p /opt/1C/v8.3/x86_64/conf
cat > /tmp/logcfg.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://v8.1c.ru/v8/tech-log">
        <log location="/home/usr1cv8/log" history="12">
                <event>
                        <ne property="Name" value=""/>
                </event>
                <property name="all"/>
        </log>
        <plansql/>
</config>
EOF
sudo cp /tmp/logcfg.xml /opt/1C/v8.3/x86_64/conf
sudo chown -R usr1cv8:grp1cv8 /opt/1C/v8.3/x86_64/conf
sudo rm -r /home/usr1cv8/log/
sudo mkdir -p /home/usr1cv8/log/
sudo chown -R usr1cv8:grp1cv8 /home/usr1cv8/log/
sudo systemctl restart srv1cv83.service
